# Generated by Django 5.0.6 on 2024-06-26 23:55

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Rol = apps.get_model("usuarios", "Rol")
    Usuario = apps.get_model("usuarios", "Usuario")
    Region = apps.get_model("usuarios", "Region")
    Comuna = apps.get_model("usuarios", "Comuna")

    # Crear regiones y comunas
    region = Region.objects.create(descripcion="Metropolitana", sigla="RM")
    comuna = Comuna.objects.create(descripcion="Santiago", region=region)

    # Crear roles
    admin_role = Rol.objects.create(descripcion="administrador", permisos=15)
    user_role = Rol.objects.create(descripcion="usuarioSinPrivilegios", permisos=1)
    custom_role = Rol.objects.create(descripcion="usuarioCustom", permisos=7)

    # Crear usuarios
    admin_user = Usuario.objects.create_user(
        username="admin",
        password="admin123",
        nombre="Admin",
        apellido="User",
        rut="12345678-9",
        dv="9",
        direccion="Admin Address",
        telefono="123456789",
        correo="admin@example.com",
        is_superuser=True,
        is_staff=True,
        rol=admin_role,
        comuna=comuna,
        region=region,
    )

    user = Usuario.objects.create_user(
        username="user",
        password="user123",
        nombre="User",
        apellido="User",
        rut="98765432-1",
        dv="1",
        direccion="User Address",
        telefono="987654321",
        correo="user@example.com",
        is_superuser=False,
        is_staff=False,
        rol=user_role,
        comuna=comuna,
        region=region,
    )

    custom_user = Usuario.objects.create_user(
        username="custom",
        password="custom123",
        nombre="Custom",
        apellido="User",
        rut="11223344-5",
        dv="5",
        direccion="Custom Address",
        telefono="1122334455",
        correo="custom@example.com",
        is_superuser=False,
        is_staff=False,
        rol=custom_role,
        comuna=comuna,
        region=region,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
